services:
  db:
    image: "postgres:${DATABASE_VERSION}"
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DATABASE: "${DATABASE_NAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - immobyte-db-data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: "immobyte-web:${IMMOBYTE_VERSION}"
    env_file:
      - .env
    user: "${USER_ID}:${GROUP_ID}"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/immobyte
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - db
volumes:
  immobyte-db-data:
