services:
  db:
    image: "postgres:${DATABASE_VERSION}"
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DATABASE: "${DATABASE_NAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    command: postgres -c log_statement=all
    volumes:
      - immobyte-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    env_file:
      - .env
    user: "${USER_ID}:${GROUP_ID}"
    command: gunicorn --bind :8000 --workers 3 immobyte.wsgi
    volumes:
      - .:/opt/immobyte
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  immobyte-db-data:
