services:
  db:
    image: "postgres:${DATABASE_VERSION}"
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DATABASE: "${DATABASE_NAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - immobyte-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: immobyte-web:1.0.0
    env_file:
      - .env
    user: "${USER_ID}:${GROUP_ID}"
    command: gunicorn --bind :8000 --workers 3 immobyte.wsgi
    volumes:
      - .:/opt/immobyte
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    image: "nginx:${NGINX_VERSION}"
    environment:
      NGINX_PORT: "${NGINX_PORT}"
      NGINX_BACKEND_SERVER: "${NGINX_BACKEND_SERVER}"
      NGINX_BACKEND_PORT: "${NGINX_BACKEND_PORT}"
      NGINX_ADMIN_IP: "${NGINX_ADMIN_IP}"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./nginx/log:/var/log/nginx/
    ports:
      - "${NGINX_BACKEND_PORT}:${NGINX_PORT}"
    depends_on:
      - web
volumes:
  immobyte-db-data:
